name: PlayerBalance
version: '${version}'
main: me.lulu.playerbalance.PlayerBalance
api-version: 1.19
author: Datou (JerryLin)

commands:
  balance:
    description: Check your balance
    aliases: [ bal ]

  givebalance:
    description: Give money to player
    aliases: [ givebal ]