name: PlayerBalance
version: '${version}'
main: me.lulu.playerbalance.PlayerBalance
api-version: 1.19
author: Datou (JerryLin)

commands:
  balance:
    description: Check your balance
    usage: /balance
    aliases: [ bal ]